### ISSUE TITLE
Merge changes from CSIRO repo

### ISSUE THREAD

**Issue by dr-shorthair** [GeoscienceAustralia/Place-Names#1]
Recent updates have been made in https://github.com/CSIRO-enviro-informatics/placenames-profile . That should be merged into this version, and one or other of the two repos should be archived.

**Comment by nicholascar** [comment]
@alex-ip please could you or Will merge changes across? In fact you will find it much easier to clone the CSIRO one into GA, perhaps as .../PlaceNames, and archive this one (viz. .../Place-Names) with a handoff note to the new one since the Git histories are difference so merging will be hard.

When done we (Simon!) will archive the CSIRO repo.

**Comment by dr-shorthair** [comment]
I have created a PR #3 that, if merged, will get the changes from the CSIRO repo, and close this Issue. 
I've already archived the CSIRO repo.
